sudo: required
services: 
  - docker

before_install:
  - docker build -t datorresr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true datorresr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-700029235138"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY